### ISSUE TITLE
Usability of diktat-analysis: invalid override of rules

### ISSUE THREAD

**Issue by akuleshov7** [analysis-dev/diktat#1146]
The following config would be treated as `name: TRAILING_COMMA enabled: true`

```
- name: TRAILING_COMMA
  enabled: true
  configuration:
    valueArgument: true
    valueParameter: true

# https://github.com/diktat-static-analysis/diKTat/issues/1106
- name: TRAILING_COMMA
  enabled: false
```
